services:

  elastic:
    image: elasticsearch:8.6.2
    container_name: elastic
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    attach: false

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    attach: false

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - 8000:8000
    depends_on:
      - redis
      - elastic
